travis:
  secure:
    BINSTAR_TOKEN: eCAAnP6zAzSa8BjsmwyrkTjY69P+QyOD8i5BMowkfNuY+LREX2qK6rv75048pSnSThjBgla4pMKYUO4AVAc5CLwUJpo3EiU3ND7181DCoLsvF4Bt5cj7VHbYQ6dCh+jwrtM4z0taDWq4M/CNLnXsOlKSv/0ShZoRlWxmNYcXjH09Uv1ElBcHHe4O18n8gC5MLs4dKNvVzRTRSWG3YzKjRSnqWYnKxFLtoTf5lV/UZD1eSq6N4iv2ts8G70dxwe5r5AAOV9U0hMs9nvBnylNgo+5e4xciI/xTtJBBdZp0HjLW/uwZ6+n+gQbuIhLF7NTkEuUr8BKW4rbTKR3A3oj04HLeBPRogA1yIVYPBKkhLNwFyFGvMdMPelTg0j1Z/isVNv3rnI3vjT302f3k2t6Abav7NdNpY4QJc6lqkNUT3/cA2+PMZdGHz275Iq8MClO17l0nyoeIfcfeoGudtwaEGUN+g0BhlTfEH3s5hHCIYenWXrWskekOQI7c3qFrrHahKk6p84fdxnXSJtKNuWr2GyArx+4UGH2KfJC3DH06ZVZ1lH7N+WuxspCloPhK+zMvEXCCMJsBQITsU6lOy48i6UGrR3/CmNtwV22UMHHbPJGWya38FwW0k5/2FlBCSGCd2NIZTb++6Ve3/st9giCChDBiw8zoSntwZ7oJUmKv97w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
